### ISSUE TITLE
[Feature Request]: Set Windows control overley height

### ISSUE THREAD

**Issue by theolivenbaum** [WICG/window-controls-overlay#23]
Hi, 

I just wanted to ask if there was any progress on the [open question](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md#open-questions-overlaying-window-controls) regarding customizing the titlebar height, to enable a similar scenario as used by Teams and many other apps:

![image](https://user-images.githubusercontent.com/8791811/132809727-7eaeca37-3dbd-4424-927b-3a9f8d873566.png)

I'm asking because this open question is currently [blocking adoption on Electron](https://github.com/electron/electron/issues/30857).

**Comment by amandabaker** [comment]
Currently, we do not plan to make the titlebar height customizable for WCO + installed web apps. We had discussed it initially, but decided not to implement it for a couple reasons:
- It may be complex to support depending on the browser's implementation.
- The spec would need to provide a way to both set and *get* the height, since the browser could reject the value (e.g. dev sets height to 0, but browser needs to show window controls). 

I'll remove the open question from the explainer so that there is no longer a concern about WCO development in the browser clashing with Electron additions.

**Comment by amandabaker** [comment]
Removed the "Open Questions" section with #25
