### ISSUE TITLE
Current Status / Future Plans or Testing

### ISSUE THREAD

**Issue by Offroaders123** [WICG/window-controls-overlay#7]
Hello,

I have been really interested in seeing something like this being implemented, and I was wondering what the current state of this  proposal is in? I have been thinking about creating an Electron package to release alongside my existing PWA to be able to use various features like this on desktop, but I'd rather stay focused on the web platform if possible because of the great potential that it has, thanks to new ideas like this. I recently found an [article on web.dev](https://web.dev/deprecating-excalidraw-electron/) about why PWAs are the future beyond Electron, and I think they brought up some very strong points there. This would be a very helpful next step in regards of what PWAs have the ability to do, compared to Electron apps.

Thanks!
Brandon Bennett

**Comment by ahsane** [comment]
Indeed, as a developer, I'm also interested in the feature.

If there's anyone from Chromium/Microsoft who can give an update that would be very helpful. 

Electron or Chromium depends on this feature for us. The UX without this isn't good enough.

**Comment by Offroaders123** [comment]
Looks like there has been some new information about the future of this proposal! I will add more references I found to it to this post, as I have come across multiple discussions that bring it up, and when it is supposed to be rolled out.

[Fugu API Tracker](https://fugu-tracker.web.app/) (Search for: Window Controls Overlay for Installed Desktop Web Apps)

**Comment by Offroaders123** [comment]
I'm not sure whether the information was present before or whether it appeared in the past two days since my last comment, but the section about this proposal on Fugu API Tracker appears to show that this API may be available to start working with in the latest Chrome 91 - 93 betas on Linux, Windows, Chrome OS, and macOS. I have yet to see if it works myself, but I thought I'd share that I noticed this, just in case anyone else is as eager to try it as myself! Personally I am curious to see how it will behave on macOS in particular, because there haven't been any demo screenshots in the explainer on what it will look like on macOS.

![Proposal status on Fugu API Tracker](https://user-images.githubusercontent.com/65947371/110151821-c85bf180-7d95-11eb-993d-c65259cebdf5.png)

**Comment by Offroaders123** [comment]
Got a little ahead of myself, the Chrome 91 beta doesn't release until April 22.
Source - [Chrome Platform Status](https://www.chromestatus.com/features/schedule)

![Chrome 91 release timeline](https://user-images.githubusercontent.com/65947371/110172633-47f7b980-7db2-11eb-8259-42f6d1db4980.png)

**Comment by amandabaker** [comment]
Hey @Offroaders123,

Many apologies for the (very) delayed response, but all the docs you linked to are correct. In addition, you can follow updates to this [CRBug](https://bugs.chromium.org/p/chromium/issues/detail?id=937121) for more granular updates on changes pushed to Chromium.

The UI portions of the feature (showing an overlay instead of the full title bar) have not yet been implemented in Chromium, so the feature as a whole isn't quite testable yet. The JS APIs and CSS env()s exist, but return an empty rect/insets of 0 since the overlay isn't visible. That said, we are actively working on the feature and are aiming to start origin trials in the m91 release and ship the feature in m94. 

With respect to Mac, I'll get a screenshot added to the explainer to show what it will look like on Mac. For now, here's a mock of what it will look like (although the padding around the settings "..." button will probably be slightly different):
![image](https://user-images.githubusercontent.com/8602218/110179456-f30d7080-7dbc-11eb-8b48-b1f01321d45b.png)
 
Since the window controls will be in the upper left and the settings "..." menu is normally in the upper right for PWAs, Mac requires two overlays. The JS APIs and CSS env()s describe the area between these two overlays.

**Comment by Offroaders123** [comment]
Thanks for the update and macOS demo image! Looking forward to start testing with it.

I'm happy to see that it behaves in a similar fashion to that of the `env(safe-area-inset-*)` properties for mobile devices too, as the `env()` function allows it to be really customizable to what elements should be sized, that was a good decision.

Also, has the decision been made to whether the inset rects will be developer-resizable? I read that it was in consideration in one of the threads somewhere about the API. If anything, the ability to making the inset rects larger to align with the height of the web app's HTML header would be the most helpful option in my opinion.

Also also, the Fugu API Tracker says that the API will be available through an origin trial once it is released as part of the Chrome 91+ betas. Will developers be able to activate it through `chrome://flags` as well?

Thanks for the response!

**Comment by Offroaders123** [comment]
The API appears to be in active development in the Chrome 92 Canary updates! Now that we know the API has a promising future, I'll go ahead and close this thread 🚀
